<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260322075051 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            'CREATE TABLE accounting_transaction (
        id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        event_id INT NOT NULL,
        account account_type NOT NULL,
        direction direction_type NOT NULL,
        amount NUMERIC(18, 2) NOT NULL,
        currency VARCHAR(3) NOT NULL,
        event_timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
        created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
        PRIMARY KEY (id))'
        );
        $this->addSql('CREATE INDEX IDX_E88BF0171F7E88B ON accounting_transaction (event_id)');
        $this->addSql('CREATE TABLE event_processed (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_id VARCHAR(255) NOT NULL,payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A16E25B671F7E88B ON event_processed (event_id)');
        $this->addSql('ALTER TABLE accounting_transaction ADD CONSTRAINT FK_E88BF0171F7E88B FOREIGN KEY (event_id) REFERENCES event_processed (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE accounting_transaction DROP CONSTRAINT FK_E88BF0171F7E88B');
        $this->addSql('DROP TABLE accounting_transaction');
        $this->addSql('DROP TABLE event_processed');
    }
}
